name       : silver-searcher
version    : 2.0.0
release    : 6
source     :
    - https://geoff.greer.fm/ag/releases/the_silver_searcher-2.0.0.tar.gz : 003387ebbfdde545841103d0ef812f30a5501a984afb3d5b45fb55714b1e9513
license    : Apache-2.0
component  : programming.tools
summary    : A code searching tool similar to ack, with a focus on speed.
description: |
    A code searching tool similar to ack, with a focus on speed.
builddeps  :
    - pkgconfig(liblzma)
    - pkgconfig(libpcre)
    - pkgconfig(zlib)
setup      : |
    %configure \
        --enable-lzma \
        --enable-zlib
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/share/the_silver_searcher $installdir/usr/share/bash-completion
