name       : silver-searcher
version    : 1.0.2
release    : 4
source     :
    - https://geoff.greer.fm/ag/releases/the_silver_searcher-1.0.2.tar.gz : 6f4a78e1f1dfa5434c19e5a585ac8cefee69986f90920928498217b36b84a46c
license    : Apache-2.0
component  : programming.tools
summary    : A code searching tool similar to ack, with a focus on speed.
description: |
    A code searching tool similar to ack, with a focus on speed.
builddeps  :
    - pkgconfig(liblzma)
    - pkgconfig(libpcre)
    - pkgconfig(zlib)
setup      : |
    %configure \
        --enable-lzma \
        --enable-zlib
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/share/the_silver_searcher $installdir/usr/share/bash-completion
