name       : silver-searcher
version    : 1.0.1
release    : 3
source     :
    - http://geoff.greer.fm/ag/releases/the_silver_searcher-1.0.1.tar.gz : d9682a70f5842197d10391e9b857576c9b6fc4e930cd6d241c249e7b4982f2ca
license    : Apache-2.0
component  : programming.tools
summary    : A code searching tool similar to ack, with a focus on speed.
description: |
    A code searching tool similar to ack, with a focus on speed.
builddeps  :
    - pkgconfig(liblzma)
    - pkgconfig(libpcre)
    - pkgconfig(zlib)
setup      : |
    %configure \
        --enable-lzma \
        --enable-zlib
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/share/the_silver_searcher $installdir/usr/share/bash-completion
