name       : silver-searcher
version    : 0.31.0
release    : 1
source     :
    - http://geoff.greer.fm/ag/releases/the_silver_searcher-0.31.0.tar.gz : 2b556d61a702d04e2638532aba08bccf178523b6a38464a25305563581823271
license    : Apache-2.0
summary    : A code searching tool similar to ack, with a focus on speed.
description: |
    A code searching tool similar to ack, with a focus on speed.
builddeps  :
    - pkgconfig(liblzma)
    - pkgconfig(libpcre)
    - pkgconfig(zlib)
setup      : |
    %configure \
        --enable-lzma \
        --enable-zlib
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/share/the_silver_searcher $installdir/usr/share/bash-completion
