name       : silver-searcher
version    : 0.33.0
release    : 2
source     :
    - http://geoff.greer.fm/ag/releases/the_silver_searcher-0.33.0.tar.gz : 8ca680399df5ee8846a509c8a67c10ee1d5fc1a94456806a0ff9dd913b961db3
license    : Apache-2.0
component  : programming.tools
summary    : A code searching tool similar to ack, with a focus on speed.
description: |
    A code searching tool similar to ack, with a focus on speed.
builddeps  :
    - pkgconfig(liblzma)
    - pkgconfig(libpcre)
    - pkgconfig(zlib)
setup      : |
    %configure \
        --enable-lzma \
        --enable-zlib
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/share/the_silver_searcher $installdir/usr/share/bash-completion
