name       : silver-searcher
version    : 1.0.3
release    : 5
source     :
    - https://geoff.greer.fm/ag/releases/the_silver_searcher-1.0.3.tar.gz : d586f483a0e709dd383f82006495550114171719f0633a24f09fab6c8dde009e
license    : Apache-2.0
component  : programming.tools
summary    : A code searching tool similar to ack, with a focus on speed.
description: |
    A code searching tool similar to ack, with a focus on speed.
builddeps  :
    - pkgconfig(liblzma)
    - pkgconfig(libpcre)
    - pkgconfig(zlib)
setup      : |
    %configure \
        --enable-lzma \
        --enable-zlib
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/share/the_silver_searcher $installdir/usr/share/bash-completion
