name       : silver-searcher
version    : 2.2.0
release    : 10
source     :
    - https://github.com/ggreer/the_silver_searcher/archive/2.2.0.tar.gz : 6a0a19ca5e73b2bef9481c29a508d2413ca1a0a9a5a6b1bd9bbd695a7626cbf9
homepage   : https://geoff.greer.fm/ag/
license    : Apache-2.0
component  : programming.tools
summary    : A code searching tool similar to ack, with a focus on speed
description: |
    A code searching tool similar to ack, with a focus on speed.
builddeps  :
    - pkgconfig(liblzma)
    - pkgconfig(libpcre)
    - pkgconfig(zlib)
environment: |
    export CFLAGS="${CFLAGS} -fcommon" # gcc10, remove on update
setup      : |
    %reconfigure \
        --enable-lzma \
        --enable-zlib
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/share/the_silver_searcher $installdir/usr/share/bash-completion
